package headers

const (
	Accept                        = "Accept"
	AcceptCharset                 = "Accept-Charset"
	AcceptEncoding                = "Accept-Encoding"
	AcceptLanguage                = "Accept-Language"
	AcceptRanges                  = "Accept-Ranges"
	AccessControlAllowCredentials = "Access-Control-Allow-Credentials"
	AccessControlAllowHeaders     = "Access-Control-Allow-Headers"
	AccessControlAllowMethods     = "Access-Control-Allow-Methods"
	AccessControlAllowOrigin      = "Access-Control-Allow-Origin"
	AccessControlExposeHeaders    = "Access-Control-Expose-Headers"
	AccessControlMaxAge           = "Access-Control-Max-Age"
	AccessControlRequestHeaders   = "Access-Control-Request-Headers"
	AccessControlRequestMethod    = "Access-Control-Request-Method"
	Age                           = "Age"
	Allow                         = "Allow"
	Authorization                 = "Authorization"
	CacheControl                  = "Cache-Control"
	ClearSiteData                 = "Clear-Site-Data"
	Connection                    = "Connection"
	ContentDisposition            = "Content-Disposition"
	ContentEncoding               = "Content-Encoding"
	ContentLanguage               = "Content-Language"
	ContentLength                 = "Content-Length"
	ContentLocation               = "Content-Location"
	ContentRange                  = "Content-Range"
	ContentSecurityPolicy         = "Content-Security-Policy"
	ContentType                   = "Content-Type"
	Cookie                        = "Cookie"
	CrossOriginEmbedderPolicy     = "Cross-Origin-Embedder-Policy"
	CrossOriginOpenerPolicy       = "Cross-Origin-Opener-Policy"
	CrossOriginResourcePolicy     = "Cross-Origin-Resource-Policy"
	Date                          = "Date"
	ETag                          = "ETag"
	Expect                        = "Expect"
	Expires                       = "Expires"
	From                          = "From"
	Host                          = "Host"
	IfMatch                       = "If-Match"
	IfModifiedSince               = "If-Modified-Since"
	IfNoneMatch                   = "If-None-Match"
	IfRange                       = "If-Range"
	IfUnmodifiedSince             = "If-Unmodified-Since"
	LastModified                  = "Last-Modified"
	Link                          = "Link"
	Location                      = "Location"
	MaxForwards                   = "Max-Forwards"
	Origin                        = "Origin"
	Pragma                        = "Pragma"
	ProxyAuthenticate             = "Proxy-Authenticate"
	ProxyAuthorization            = "Proxy-Authorization"
	Range                         = "Range"
	Referer                       = "Referer"
	RefererPolicy                 = "Referer-Policy"
	RetryAfter                    = "Retry-After"
	SecWebsocketKey               = "Sec-WebSocket-Key"
	Server                        = "Server"
	SetCookie                     = "Set-Cookie"
	StrictTransportSecurity       = "Strict-Transport-Security"
	TE                            = "TE"
	Trailer                       = "Trailer"
	TransferEncoding              = "Transfer-Encoding"
	Upgrade                       = "Upgrade"
	UserAgent                     = "User-Agent"
	Vary                          = "Vary"
	Via                           = "Via"
	Warning                       = "Warning"
	WwwAuthenticate               = "WWW-Authenticate"
	XAccelBuffering               = "X-Accel-Buffering"
	XContentTypeOptions           = "X-Content-Type-Options"
	XForwardedFor                 = "X-Forwarded-For"
	XForwardedProto               = "X-Forwarded-Proto"
	XFrameOptions                 = "X-Frame-Options"
	XHttpMethodOverride           = "X-HTTP-Method-Override"
	XPermittedCrossDomainPolicies = "X-Permitted-Cross-Domain-Policies"
)

// ContentTypeHeader generates a Content-Type header value based on given content type and charset.
func ContentTypeHeader(contentType string, charset string) string {
	return contentType + "; charset=" + charset
}
