name: Unit tests
on: [push, workflow_dispatch]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...